### PR TITLE
Fixed Dirs change error in GenericScraper

### PR DESCRIPTION
**Pull request by PolBaladas**

### CODE REVIEW

**Comment by PolBaladas** [comment]
Can this be merged please?

**Comment by mariobehling** [comment]
Good job!

**Comment by PolBaladas** [comment]
Thanks!

Btw, should we create a separate Repo for André's Generic Scraper? (Last developed)

**Comment by mariobehling** [comment]
@PolBaladas Not sure, cause it is a very small thing. Maybe first add some info about the generic scraper into the Readme.md. Also would be great to get some sample outcome in the repo.

**Pull request merged**
